name: NPM

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - name: Build
        working-directory: packages/attilajs
        run: yarn build:prod
      # The version in the repo is always 0.0.0
      # This step updates it to the current tag before publishing the package
      - name: Update version
        working-directory: packages/attilajs
        run: sed -i "s/0.0.0/${{ github.ref_name }}/" dist/package.json
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        working-directory: packages/attilajs/dist
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
